### ISSUE TITLE
bitlocker already defined

### ISSUE THREAD

**Issue by JamesHabben** [volatilityfoundation/community#26]
Trying to run current volatility with community plugins on OSX and getting this error. Is it a conflict with one of the plugins?

`Traceback (most recent call last):
  File "/usr/local/bin/vol.py", line 4, in <module>
    __import__('pkg_resources').run_script('volatility==2.6', 'vol.py')
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 750, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1527, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python2.7/site-packages/volatility-2.6-py2.7.egg/EGG-INFO/scripts/vol.py", line 192, in <module>
    main()
  File "/usr/local/lib/python2.7/site-packages/volatility-2.6-py2.7.egg/EGG-INFO/scripts/vol.py", line 162, in main
    cmds = registry.get_plugin_classes(commands.Command, lower = True)
  File "/usr/local/lib/python2.7/site-packages/volatility-2.6-py2.7.egg/volatility/registry.py", line 152, in get_plugin_classes
    raise Exception("Object {0} has already been defined by {1}".format(name, plugin))
Exception: Object bitlocker has already been defined by <class 'volatility.plugins.ThomasWhite.bitlocker.Bitlocker'>`

**Comment by iMHLv2** [comment]
Hi James, yes it looks like two plugins have the same name. There's a note in the "usage" section of the README.md that discusses how to avoid conflicting command line arguments, and the same thing applies to plugins with conflicting names.
